#!/usr/bin/env python3
import argparse


def list_tasks():
    print("All tasks")


def create_tasks():
    print("Create new task")


def delete_task():
    print("Delete task")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('command', help='Command to run. Available commands: new, list, delete')

    args = parser.parse_args()

    command = args.command

    # TODO remove if-elif
    if command == 'list':
        list_tasks()
    elif command == 'new':
        create_tasks()
    elif command == 'delete':
        delete_task()
    else:
        print('Undefined command "{}". Use pytodo --help to learn about available commands'.format(command))
