#!/usr/bin/env python3
import argparse

import datetime

import sqlite3


def create_tasks():
    print("Create new task")

    new_note = input("Enter new note:")
    note_name = input("Choose title for this note:")

    con = sqlite3.connect("sqlite_new.db")

    cursor = con.cursor()

    cursor.execute("CREATE TABLE IF NOT EXISTS all_notes (name, note, current_id)")

    cursor.execute(
        "INSERT INTO all_notes (name, note, current_id) VALUES (?,?,?)",
        (note_name, new_note, cursor.lastrowid)
    )

    con.commit()
    cursor.close()
    con.close()

    print("You could watch your note by 'list'")


def delete_task():
    print("Delete task")


def list_tasks():
    print("All tasks")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('command', help='Command to run. Available commands: new, list, delete')

    args = parser.parse_args()

    command = args.command

    # TODO remove if-elif
    if command == 'list':
        list_tasks()
    elif command == 'new':
        create_tasks()
    elif command == 'delete':
        delete_task()
    else:
        print('Undefined command "{}". Use pytodo --help to learn about available commands'.format(command))
